# Define configuration
# Note: if relative paths are defined, they are considered as relative to this
# file's own location.
config:
  prefix: Vspi_master_tb      # Prefix
  top: spi_master_tb          # Name of top module
  verilog_src_files:          # List of Verilog source files
  - ../spi_slave.v
  - ../spi_master.v
  - ../spi_master_tb.v
  #cpp_src_files:             # Extra C++ source files
  verisocks_root: ../../..    # Verisocks root path
  verilator_path: /usr/local/bin/verilator
  verilator_root: /usr/local/share/verilator
  use_tracing: false
  use_fst: false
  log_level: debug

# Define model variables to be accessible with Verisocks commands
variables:
  scalars: # Scalar variables
  - path: spi_master_tb.i_spi_master.transaction_counter
    module: spi_master
    type: uint32
    width: 32
  arrays: # Array variables
  - path: spi_master_tb.i_spi_master.rx_buffer
    module: spi_master
    type: uint8
    width: 8
    depth: 8
  - path: spi_master_tb.i_spi_master.tx_buffer
    module: spi_master
    type: uint8
    width: 8
    depth: 7
  events: # Named events
  - path: spi_master_tb.i_spi_master.start_transaction
    module: spi_master
  - path: spi_master_tb.i_spi_master.end_transaction
    module: spi_master
  # params: # Parameters
