name: Build and publish Python Package

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build distribution packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: |
          python -m build --outdir dist python
      - name: Store distribution packages
        uses: actions/upload-artifact@v4
        with:
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/verisocks
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: dist/
      - name: Publish distribution packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1