name: Build docs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Setup environment
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./python
        pip install sphinx sphinx-rtd-theme myst-parser
    - name: Build documentation
      run: |
        sphinx-build -M html ./docs ./docs/_build

