name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Builds VPI library
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
          submodules: true
      
    - name: Install dependencies
      run: sudo apt install iverilog make libcunit1 libcunit1-dev valgrind lcov xsltproc
      
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: cunit test
      run: cd test & make
