name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
    
    - uses: awalsh128/cache-apt-pkgs-action@v1.2.2
      with:
          packages: iverilog

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
