name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds VPI library
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install iverilog
    - name: configure
      run: ./configure
    - name: make
      run: make
