name: Builds and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Builds VPI library
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install dependencies
      run: sudo apt-get update;sudo apt install iverilog make libcunit1 libcunit1-dev valgrind lcov xsltproc
    - name: configure
      run: ./configure
    - name: Build library
      run: make
    - name: Build and run cunit test
      run: cd test;make;cd ..
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: libvpi
        path: build/verisocks.vpi
    - name: Archive cunit test artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cunit-test-results
        path: |
          test/build/CUnitAutomated-Results.xml
          test/build/cunit_test_results.html
          test/build/cunit_test_valgrind.rpt

  pytest:
    needs: build
    runs-on: ubuntu-latest
    name: Run pytest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3"
    - name: Install dependencies
      run: |
        sudo apt install iverilog
        python -m pip install --upgrade pip
        pip install -e ./python
        pip install pytest pytest-cov
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: libvpi
    - name: Check verisocks.vpi
      run: |
        ls -l verisocks.vpi
        mkdir -p build
        mv verisocks.vpi build/.
    - name: Run pytest
      run: pytest -x --log-cli-level=INFO --cov=verisocks python/test/test_verisocks.py
    - name: Archive test logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs
        path: |
          pytest.log
          vvp.log
